'use strict';
// ── NB_CORPUS — Naive Bayes training corpus ───────────────────────────────────
// Extraído sin modificaciones de SafetyOps_v2.html líneas 2697-3719

const NB_CORPUS=[
  // ── Bird Strike ──────────────────────────────────────────────────────────
  ["impacto con ave a 200 pies sin daños en motor","Bird Strike"],
  ["un pájaro entró al motor izquierdo en despegue","Bird Strike"],
  ["chocamos con un pájaro al descender sobre la pista","Bird Strike"],
  ["ave ingresó al motor durante la carrera de despegue","Bird Strike"],
  ["encontramos restos de plumas y sangre en el motor derecho","Bird Strike"],
  ["gaviota impactó el parabrisas durante aproximación final","Bird Strike"],
  ["bandada de pájaros cruzó la pista y uno entró al motor","Bird Strike"],
  ["bird strike en motor 2 a 500 pies durante ascenso inicial","Bird Strike"],
  ["ave en turbina se realizó inspección post vuelo","Bird Strike"],
  ["impacto aviario confirmado por restos en nacela del motor","Bird Strike"],
  ["paloma impactó el borde de ataque del ala en ascenso","Bird Strike"],
  ["varios pájaros en la trayectoria al despegar de la 29L","Bird Strike"],
  // ── Runway Excursion ─────────────────────────────────────────────────────
  ["nos fuimos de pista al aterrizar pista mojada","Runway Excursion"],
  ["aeronave excedió límites laterales de pista en lluvia y viento cruzado","Runway Excursion"],
  ["salida de pista durante el aterrizaje por hidroplaneo","Runway Excursion"],
  ["aeronave se desvió al lateral de la pista en el aterrizaje","Runway Excursion"],
  ["corrimos la pista paramos en la zona de seguridad RESA","Runway Excursion"],
  ["frenado insuficiente en pista contaminada sobrecarrera","Runway Excursion"],
  ["nos salimos de la pista por viento cruzado excesivo","Runway Excursion"],
  ["aterrizaje largo en pista corta no frenamos a tiempo","Runway Excursion"],
  ["aeronave excedió el final de pista durante aterrizaje nocturno","Runway Excursion"],
  ["hydroplaning al aterrizar en pista con agua acumulada","Runway Excursion"],
  ["se fue de pista al despegar con falla en frenos","Runway Excursion"],
  // ── TCAS RA ──────────────────────────────────────────────────────────────
  ["aviso de resolución TCAS por tránsito convergente a 500 pies evasión ejecutada","TCAS RA"],
  ["casi chocamos con otro avión el tcas nos avisó","TCAS RA"],
  ["TCAS RA climb separación de tráfico conflictivo","TCAS RA"],
  ["resolution advisory ejecutado tráfico a 300 pies y cerrando","TCAS RA"],
  ["nos cruzamos con un avión sin comunicación ATC activó TCAS","TCAS RA"],
  ["pérdida de separación resuelta por TCAS RA descend descend","TCAS RA"],
  ["near miss aéreo con tráfico VFR TCAS intervino","TCAS RA"],
  ["conflicto de tráfico a FL280 resuelto por ACAS II","TCAS RA"],
  ["casi nos chocamos con otro avión en el descenso inicial","TCAS RA"],
  // ── Hard Landing ─────────────────────────────────────────────────────────
  ["aterrizaje brusco con alarma QAR sin lesiones","Hard Landing"],
  ["aterrizamos muy fuerte el avión rebotó","Hard Landing"],
  ["aterrizaje duro que activó inspección QAR post vuelo","Hard Landing"],
  ["tasa de descenso elevada al tocar pista excedencia QAR","Hard Landing"],
  ["el avión llegó con mucha energía y tocamos muy fuerte","Hard Landing"],
  ["golpe fuerte al aterrizar se inspeccionó el tren","Hard Landing"],
  ["landing brusco se realizó hard landing check de mantenimiento","Hard Landing"],
  ["porpoise en el aterrizaje rebotamos dos veces","Hard Landing"],
  ["FDR indica excedencia de g en touchdown inspección requerida","Hard Landing"],
  // ── Unstable Approach ────────────────────────────────────────────────────
  ["aproximación fuera de parámetros estabilizados bajo 500 pies go-around","Unstable Approach"],
  ["hicimos go-around porque íbamos muy rápido en final","Unstable Approach"],
  ["continuamos una aproximación inestabilizada no cumplía gate de estabilización","Unstable Approach"],
  ["íbamos demasiado altos y rápidos en final abortamos el aterrizaje","Unstable Approach"],
  ["vref excedida en final se ejecutó go around de inmediato","Unstable Approach"],
  ["aproximación no estabilizada se discontinuó y se realizó circuito","Unstable Approach"],
  ["exceso de energía en final no pudimos estabilizar antes del umbral","Unstable Approach"],
  ["glideslope desviado por debajo de lo autorizado continuamos sin estabilizar","Unstable Approach"],
  // ── GPWS ─────────────────────────────────────────────────────────────────
  ["alarma GPWS Terrain Pull Up en aproximación nocturna baja visibilidad","GPWS"],
  ["se activó gpws en aproximación por descenso excesivo","GPWS"],
  ["sonó la alarma de terreno durante la aproximación al cerro","GPWS"],
  ["EGPWS terrain terrain evasión ejecutada","GPWS"],
  ["whoop whoop pull up activado a 800 pies AGL","GPWS"],
  ["alerta CFIT durante aproximación en valle montañoso con IMC","GPWS"],
  ["minimum safe altitude warning activada por ATC baja visibilidad","GPWS"],
  ["TAWS modo 1 activado sink rate excesivo en aproximación","GPWS"],
  // ── Ground Damage ─────────────────────────────────────────────────────────
  ["daño en fuselaje por equipo de rampa durante carga","Ground Damage"],
  ["un vehículo golpeó el ala izquierda en la rampa durante el pushback","Ground Damage"],
  ["loader chocó contra el fuselaje durante la carga de equipaje","Ground Damage"],
  ["manga del aeropuerto golpeó el avión al acoplar","Ground Damage"],
  ["encontramos una abolladura en el fuselaje al llegar a hangar","Ground Damage"],
  ["el tractor de remolque dañó el tren de nariz durante el pushback","Ground Damage"],
  ["colisión entre vehículo de rampa y aeronave en plataforma","Ground Damage"],
  ["daño en wingtip por contacto con otra aeronave en rodaje","Ground Damage"],
  ["GPU contactó el fuselaje al conectarse antes del vuelo","Ground Damage"],
  // ── Falla Técnica ─────────────────────────────────────────────────────────
  ["falla sistema hidráulico en vuelo checklist aplicado aterrizaje sin incidentes","Falla Técnica"],
  ["turbina en llamas durante vuelo piloto activó extintor","Falla Técnica"],
  ["perdimos un motor en ascenso inicial aterrizaje de emergencia","Falla Técnica"],
  ["falla eléctrica total en crucero procedimiento de emergencia activado","Falla Técnica"],
  ["el tren de aterrizaje no bajó se realizó procedimiento de emergencia","Falla Técnica"],
  ["presurización perdida en crucero máscaras de oxígeno desplegadas","Falla Técnica"],
  ["vibración excesiva en motor derecho shutdown en vuelo","Falla Técnica"],
  ["derrame de combustible detectado en ala izquierda durante vuelo","Falla Técnica"],
  ["humo eléctrico en cabina de pasajeros aterrizaje de emergencia","Falla Técnica"],
  ["el piloto automático se desconectó inesperadamente en crucero","Falla Técnica"],
  ["ruido extraño en el motor al despegar inspección requerida","Falla Técnica"],
  ["grieta en el fuselaje encontrada en inspección visual post-vuelo","Falla Técnica"],
  // ── Factores Humanos ──────────────────────────────────────────────────────
  ["copiloto reporta fatiga acumulada por secuencia extendida sin descanso","Factores Humanos"],
  ["piloto se distrajo y olvidó el checklist de despegue","Factores Humanos"],
  ["tripulación fatigada luego de 14 horas de servicio","Factores Humanos"],
  ["error de coordinación entre piloto y copiloto en aproximación","Factores Humanos"],
  ["confusión de aeropuerto durante programación del FMS","Factores Humanos"],
  ["omisión de ítem en checklist de despegue por distracción","Factores Humanos"],
  ["pasajero agresivo a bordo tripulación solicitó asistencia policial","Factores Humanos"],
  ["emergencia médica a bordo pasajero con paro cardíaco","Factores Humanos"],
  ["tripulante reporta somnolencia durante vuelo nocturno","Factores Humanos"],
  ["mala comunicación entre torre y tripulación derivó en confusión de pista","Factores Humanos"],
  ["copiloto no reportó desviación del perfil hasta tarde","Factores Humanos"],
  // ── Turbulencia ───────────────────────────────────────────────────────────
  ["turbulencia severa inesperada en crucero FL350 lesiones a tripulante no asegurado","Turbulencia"],
  ["los pasajeros cayeron por turbulencia fuerte alguien se golpeó la cabeza","Turbulencia"],
  ["encontramos turbulencia severa sin reporte previo de SIGMET","Turbulencia"],
  ["windshear en final a 300 pies se ejecutó go around","Turbulencia"],
  ["pasajeros sin cinturón resultaron heridos por turbulencia moderada","Turbulencia"],
  ["tormenta eléctrica severa en ruta obligó desvío de emergencia","Turbulencia"],
  ["baja visibilidad por niebla espesa impidió aproximación","Turbulencia"],
  ["granizo impactó la aeronave en ascenso inicial daño en radomo","Turbulencia"],
  ["clear air turbulence sin advertencia previa lesionó a auxiliar de vuelo","Turbulencia"],
  // ── Seguridad Aeroportuaria ───────────────────────────────────────────────
  ["persona tomando vino en la pista de aterrizaje","Seguridad Aeroportuaria"],
  ["robo de laptop a pasajero en sala de embarque","Seguridad Aeroportuaria"],
  ["acceso no autorizado a zona de rampa por puerta sin control","Seguridad Aeroportuaria"],
  ["encontraron un objeto sospechoso en sala de preembarque","Seguridad Aeroportuaria"],
  ["persona sin identificación ingresó a zona airside","Seguridad Aeroportuaria"],
  ["conductor de vehículo de rampa con olor a alcohol","Seguridad Aeroportuaria"],
  ["amenaza de bomba anónima en terminal evacuación activada","Seguridad Aeroportuaria"],
  ["pasajero intentó abrir puerta de emergencia durante el vuelo","Seguridad Aeroportuaria"],
  ["hurto de efectivo a pasajero en cinta de embarque","Seguridad Aeroportuaria"],
  ["hombre no identificado encontrado en plataforma de rodaje","Seguridad Aeroportuaria"],
  ["se encuentra un bolso dejado en el suelo de forma extraña cerca de la puerta de ingreso","Seguridad Aeroportuaria"],
  ["mochila dejada sola en sala de espera sin dueño visible","Seguridad Aeroportuaria"],
  ["bolso tirado en el piso cerca del acceso a la terminal nadie lo reclama","Seguridad Aeroportuaria"],
  ["encontramos un paquete abandonado en la puerta de embarque","Seguridad Aeroportuaria"],
  ["bulto sospechoso dejado en el baño de la terminal fue evacuado el sector","Seguridad Aeroportuaria"],
  ["valija sin etiqueta encontrada en la zona de retiro de equipaje sin dueño","Seguridad Aeroportuaria"],
  ["cámara de seguridad reveló individuo en área restringida airside","Seguridad Aeroportuaria"],
  // ── Amenazas explosivas / interferencia ilícita en vuelo ─────────────────
  // ── Interferencia Ilícita (en vuelo) ────────────────────────────────────
  ["posibles explosivos encontrados en el baño del avión en pleno vuelo","Interferencia Ilícita"],
  ["arma en el avión pleno vuelo tripulación activó protocolo","Interferencia Ilícita"],
  ["amenaza en el avión en pleno vuelo","Interferencia Ilícita"],
  ["tripulación encontró artefacto sospechoso en baño de aeronave durante crucero","Interferencia Ilícita"],
  ["pasajero amenazó con detonar explosivo a bordo del vuelo","Interferencia Ilícita"],
  ["se encontró objeto con apariencia de bomba en lavabo de cabina en vuelo","Interferencia Ilícita"],
  ["amenaza de bomba a bordo durante vuelo en ruta declaración de emergencia","Interferencia Ilícita"],
  ["pasajero portaba material explosivo detectado por tripulación de cabina","Interferencia Ilícita"],
  ["dispositivo explosivo improvisado IED encontrado en equipaje de mano en vuelo","Interferencia Ilícita"],
  ["nota amenazante con mención de explosivos hallada en asiento de aeronave en vuelo","Interferencia Ilícita"],
  ["pasajero dijo tener bomba en vuelo tripulación activó protocolo de seguridad","Interferencia Ilícita"],
  ["granada o artefacto similar encontrado en equipaje de cabina durante el vuelo","Interferencia Ilícita"],
  ["pasajero intentó abrir puerta de emergencia durante el vuelo","Interferencia Ilícita"],
  ["pasajero con cuchillo detectado a bordo en pleno vuelo","Interferencia Ilícita"],
  ["pasajero intentó acceder a cabina de mando durante el vuelo","Interferencia Ilícita"],
  // ── Incursión de Pista ────────────────────────────────────────────────────
  ["aeronave cruzó pista activa sin clearance ATC","Incursión de Pista"],
  ["vehículo de rampa entró a la pista sin autorización de torre","Incursión de Pista"],
  ["tomamos la pista equivocada por confusión de taxeo","Incursión de Pista"],
  ["otro avión se metió en la pista mientras despegábamos","Incursión de Pista"],
  ["confusión entre tower y tripulación derivó en incursión de pista activa","Incursión de Pista"],
  ["nos quedamos parados en la pista sin autorización de cruce","Incursión de Pista"],
  ["aeronave en pista sin autorización detectada por RWSL","Incursión de Pista"],
  ["hotspot A3 cruzamos sin clearance por read-back erróneo","Incursión de Pista"],
  // ── Demora Operacional ────────────────────────────────────────────────────
  ["salimos con 90 minutos de atraso por catering que no llegó","Demora Operacional"],
  ["demora de 2 horas por falla en el jetway","Demora Operacional"],
  ["delay de 45 minutos por documentación incompleta de carga","Demora Operacional"],
  ["perdimos el slot por retraso en el boarding","Demora Operacional"],
  ["rotación demorada por limpieza extendida y equipaje rezagado","Demora Operacional"],
  // ── Bird Strike — EN/ES expansión ───────────────────────────────────────
  ["bird hit the engine on takeoff roll","Bird Strike"],
  ["flock of birds ingested into both engines during climb","Bird Strike"],
  ["bird strike on windshield during final approach","Bird Strike"],
  ["feathers and blood found on leading edge after landing","Bird Strike"],
  ["wildlife strike caused engine surge and shut down","Bird Strike"],
  ["goose struck left engine at 3000 feet","Bird Strike"],
  ["bird ingestion engine 1 runway 28R departure","Bird Strike"],
  ["we hit a large bird on short final feathers on nose","Bird Strike"],
  ["avian wildlife impact confirmed by post-flight inspection","Bird Strike"],
  ["raptor strike on empennage no structural damage","Bird Strike"],
  ["buitre impactó el empuje trasero sin daño aparente","Bird Strike"],
  ["ave de gran porte ingresó turbina 1 en trayectoria de despegue","Bird Strike"],
  ["cigüeña colisionó con el parabrisas en final de pista 10","Bird Strike"],
  // ── Runway Excursion — EN/ES expansión ──────────────────────────────────
  ["aircraft departed the runway surface during landing roll","Runway Excursion"],
  ["overran the runway end and stopped on RESA","Runway Excursion"],
  ["veered left off the centerline in crosswind landing","Runway Excursion"],
  ["aquaplaning caused loss of directional control on wet runway","Runway Excursion"],
  ["runway excursion during rejected takeoff brakes failed","Runway Excursion"],
  ["off-runway excursion grass area no injuries","Runway Excursion"],
  ["loss of steering on landing rollout departed paved surface","Runway Excursion"],
  ["aircraft skidded off the runway on contaminated surface","Runway Excursion"],
  ["salimos del pavimento en el aterrizaje por frenado tardío","Runway Excursion"],
  ["excursión lateral de pista por ráfaga de viento al tocar","Runway Excursion"],
  ["aeronave se detuvo en área de seguridad RESA tras sobrecarrera","Runway Excursion"],
  // ── TCAS RA — EN/ES expansión ───────────────────────────────────────────
  ["received TCAS climb RA and complied immediately","TCAS RA"],
  ["TCAS resolution advisory descent issued at FL280","TCAS RA"],
  ["traffic alert followed by RA climb we executed","TCAS RA"],
  ["near miss TCAS RA issued other aircraft did not comply","TCAS RA"],
  ["RA triggered at FL310 ATC unaware of conflicting traffic","TCAS RA"],
  ["TCAS RA resolved conflict with unknown aircraft below","TCAS RA"],
  ["both aircraft received crossing RA successfully resolved","TCAS RA"],
  ["aviso de resolución TCAS a FL240 ejecutado subida","TCAS RA"],
  ["alerta de tráfico seguida de RA descendemos 500 fpm","TCAS RA"],
  ["TCAS generó RA de cruce ATC no informado del tráfico","TCAS RA"],
  ["RA de TCAS ignorado por el otro tráfico separación mínima","TCAS RA"],
  // ── Hard Landing — EN/ES expansión ──────────────────────────────────────
  ["hard landing exceeded limit load engineering inspection required","Hard Landing"],
  ["firm arrival triggered hard landing check","Hard Landing"],
  ["g-load exceedance on touchdown hard landing report filed","Hard Landing"],
  ["heavy touchdown passengers felt strong impact","Hard Landing"],
  ["hard landing in gusty crosswind exceeded 1.8g","Hard Landing"],
  ["structural inspection required after abnormal touchdown g-load","Hard Landing"],
  ["we exceeded the hard landing threshold on runway 36","Hard Landing"],
  ["aterrizaje duro supera el límite de carga requiere inspección","Hard Landing"],
  ["toque brusco en pista mojada superó el g máximo establecido","Hard Landing"],
  ["aterrizaje fuerte con ráfaga a mitad de flare g excedido","Hard Landing"],
  ["excedimos la carga g límite en el aterrizaje inspeccionaron tren","Hard Landing"],
  // ── Unstable Approach — EN/ES expansión ─────────────────────────────────
  ["approach unstabilized below 1000ft continued to land","Unstable Approach"],
  ["did not meet stabilization criteria executed go-around","Unstable Approach"],
  ["excessive speed on final gate not captured go around executed","Unstable Approach"],
  ["continued approach despite unstable conditions callout ignored","Unstable Approach"],
  ["high descent rate on final approach not corrected","Unstable Approach"],
  ["glideslope deviation below 500ft not called out","Unstable Approach"],
  ["airspeed 30 knots above Vref on final did not go around","Unstable Approach"],
  ["aproximación inestable continuamos el aterrizaje sin hacer go-around","Unstable Approach"],
  ["velocidad excesiva en final superamos los parámetros de estabilización","Unstable Approach"],
  ["desvío de senda de planeo en final no anunciado ni corregido","Unstable Approach"],
  ["no cumplimos criterios de aproximación estabilizada bajo los 500 pies","Unstable Approach"],
  // ── GPWS ─────────────────────────────────────────────────────────────────
  ["GPWS warning pull up maneuver executed immediate climb","GPWS"],
  ["terrain warning activated during descent in mountainous area","GPWS"],
  ["EGPWS alert sink rate crew responded with immediate go-around","GPWS"],
  ["too low terrain alert triggered on non-precision approach","GPWS"],
  ["GPWS mode 2 activation below minimums unexpected terrain","GPWS"],
  ["ground proximity warning system alerted on initial approach","GPWS"],
  ["alertas de EGPWS pull-up maniobra de escape ejecutada","GPWS"],
  ["alarma de terreno GPWS activada al descender por debajo del mínimo","GPWS"],
  ["aviso GPWS modo 2 senda de aproximación incorrecta",  "GPWS"],
  ["TAWS alertó proximidad terreno maniobra de escape exitosa","GPWS"],
  // ── Ground Damage — EN/ES expansión ─────────────────────────────────────
  ["ground equipment struck the aircraft fuselage during pushback","Ground Damage"],
  ["jet bridge contacted the forward fuselage door area","Ground Damage"],
  ["baggage loader hit the lower fuselage causing visible dent","Ground Damage"],
  ["fuel truck mirror clipped the wingtip during ramp operations","Ground Damage"],
  ["catering truck contacted the aircraft skin paint damage only","Ground Damage"],
  ["pushback tug collided with nose gear damage to fuselage","Ground Damage"],
  ["GSE vehicle struck the main landing gear fairing","Ground Damage"],
  ["ground damage by ramp vehicle engine cowling scraped","Ground Damage"],
  ["pasarela golpeó el fuselaje delantero al acoplarse abolladura","Ground Damage"],
  ["tractor de remolque impactó el tren de morro daño estructural menor","Ground Damage"],
  ["carro de equipaje rozó la piel del fuselaje abolladura visible","Ground Damage"],
  ["cisterna de combustible golpeó el winglet durante el abastecimiento","Ground Damage"],
  // ── Falla Técnica — EN/ES expansión ─────────────────────────────────────
  ["hydraulic system low pressure light illuminated in cruise","Falla Técnica"],
  ["ECAM warning hydraulic green system failure crew drill performed","Falla Técnica"],
  ["engine number two oil pressure low returned to base","Falla Técnica"],
  ["autopilot disconnected unexpectedly during climb","Falla Técnica"],
  ["fuel pump low pressure caution light came on in flight","Falla Técnica"],
  ["electrical bus failure shed non-essential systems","Falla Técnica"],
  ["landing gear warning light stuck no gear extension anomaly","Falla Técnica"],
  ["smoke detector activated in cargo hold crew executed checklist","Falla Técnica"],
  ["falla en sistema hidráulico 1 lista de verificación ejecutada","Falla Técnica"],
  ["indicador de baja presión de aceite motor 2 aterrizaje precautorio","Falla Técnica"],
  ["piloto automático desconectó sin causa aparente en crucero","Falla Técnica"],
  ["alarma de humo en bodega de carga procedimiento ejecutado","Falla Técnica"],
  ["EICAS mostró falla de bomba de combustible vuelo continuado","Falla Técnica"],
  // ── Factores Humanos — EN/ES expansión ──────────────────────────────────
  ["crew fatigue affected performance extended duty day 16 hours","Factores Humanos"],
  ["communication breakdown between captain and first officer","Factores Humanos"],
  ["checklist omitted due to time pressure on pushback","Factores Humanos"],
  ["pilot read-back error from ATC caused altitude deviation","Factores Humanos"],
  ["distraction during taxi led to runway incursion attempt","Factores Humanos"],
  ["complacency in high-automation environment checklist skipped","Factores Humanos"],
  ["mode confusion in autopilot resulted in altitude bust","Factores Humanos"],
  ["error de cabina por presión del tiempo omitimos la lista preflight","Factores Humanos"],
  ["malentendido entre piloto y controlador instrucción mal comprendida","Factores Humanos"],
  ["fatiga acumulada por doble turno afectó la concentración","Factores Humanos"],
  ["distracción en rodaje por discusión de procedimiento checklist omitida","Factores Humanos"],
  // ── Factores Humanos — uniforme / indumentaria / EPP / SOP (fix v2) ─────
  ["piloto sin uniforme reglamentario en cabina de mando","Factores Humanos"],
  ["tripulante sin ropa reglamentaria para operar la aeronave","Factores Humanos"],
  ["copiloto no llevaba la indumentaria correspondiente al vuelo","Factores Humanos"],
  ["piloto sin chaleco de seguridad en zona de rampa","Factores Humanos"],
  ["tripulación sin equipo de protección personal requerido","Factores Humanos"],
  ["personal sin uniforme reglamentario detectado en cabina","Factores Humanos"],
  ["piloto no vestía la ropa adecuada para efectuar el vuelo","Factores Humanos"],
  ["tripulante sin indumentaria autorizada para operar en cabina","Factores Humanos"],
  ["omisión de EPP reglamentario por parte de tripulante de vuelo","Factores Humanos"],
  ["incumplimiento de normas de vestimenta en tripulación de cabina","Factores Humanos"],
  ["pilot not wearing required uniform for cockpit operations","Factores Humanos"],
  ["crew member lacked proper attire for flight operations","Factores Humanos"],
  ["flight crew uniform violation detected prior to departure","Factores Humanos"],
  ["secuencia incorrecta en el procedimiento de pre-vuelo","Factores Humanos"],
  ["secuencias de checklist ejecutadas en orden incorrecto","Factores Humanos"],
  ["tripulación ejecutó checklist prevuelo en secuencia equivocada","Factores Humanos"],
  ["orden incorrecto de ítems en procedimiento pre-vuelo","Factores Humanos"],
  ["error de secuencia en el walk-around pre-vuelo","Factores Humanos"],
  ["procedimiento de pre-vuelo realizado con pasos omitidos","Factores Humanos"],
  ["ítem del checklist pre-vuelo realizado fuera de secuencia","Factores Humanos"],
  ["inversión de pasos en procedimiento pre-vuelo por distracción","Factores Humanos"],
  ["wrong sequence in pre-flight checklist execution","Factores Humanos"],
  ["pre-flight procedure steps completed out of order","Factores Humanos"],
  ["crew executed pre-departure checklist in incorrect sequence","Factores Humanos"],
  ["piloto incumplió normas operacionales vigentes antes del vuelo","Factores Humanos"],
  ["tripulante violó procedimiento estándar de operaciones","Factores Humanos"],
  ["desviación de SOP detectada en tripulación antes de vuelo","Factores Humanos"],
  ["incumplimiento de norma operacional por parte del comandante","Factores Humanos"],
  ["violación de disciplina de cabina por piloto en servicio","Factores Humanos"],
  // apariencia / estado uniforme / azafata
  ["azafata con uniforme arrugado antes del embarque","Factores Humanos"],
  ["sobrecargo no cumple con la presentación personal requerida","Factores Humanos"],
  ["tripulante de cabina con uniforme en mal estado","Factores Humanos"],
  ["azafata con ropa sucia durante el vuelo","Factores Humanos"],
  ["auxiliar de vuelo con uniforme deteriorado detectado","Factores Humanos"],
  ["tripulación de cabina con presentación inadecuada","Factores Humanos"],
  ["flight attendant uniform not meeting company standards","Factores Humanos"],
  ["cabin crew member appearance did not meet dress code","Factores Humanos"],
  ["uniforme de azafata no cumple los estándares reglamentarios","Factores Humanos"],
  ["sobrecargo detectado con ropa arrugada y aspecto inapropiado","Factores Humanos"],
  // daño a equipo causado por acción humana — causa FH, consecuencia FT
  ["la azafata rompió el computador de abordo durante el vuelo","Factores Humanos"],
  ["tripulante de cabina dañó panel de control por manipulación incorrecta","Factores Humanos"],
  ["sobrecargo golpeó accidentalmente el sistema de entretenimiento y lo averió","Factores Humanos"],
  ["auxiliar de vuelo derramó líquido sobre equipo aviónico causando falla","Factores Humanos"],
  ["cabin crew member accidentally broke the IFE system panel","Factores Humanos"],
  ["flight attendant damaged avionics panel during cabin service","Factores Humanos"],
  ["tripulante operó incorrectamente el equipo causando daño al sistema","Factores Humanos"],
  ["acción del personal de cabina resultó en falla del sistema de comunicaciones","Factores Humanos"],
  ["crew member mishandled equipment resulting in system failure","Factores Humanos"],
  ["piloto aplicó input excesivo causando daño estructural en maniobra","Factores Humanos"],
  // ── NASA ASRS — Factores Humanos reales ────────────────────────────────
  ["captain was on autopilot mentally and parked aircraft without guide man against SOP","Factores Humanos"],
  ["crew distracted by MEL review during towing lost situational awareness of movement","Factores Humanos"],
  ["communications breakdown with mechanic during pushback led to near ramp excursion","Factores Humanos"],
  ["pilot continued taxiing while investigating cockpit smoke instead of stopping","Factores Humanos"],
  ["ramp crew pressure for on-time departure led to skipping dangerous goods procedure","Factores Humanos"],
  ["comandante operó en modo automático mental y estacionó sin guía de rampa","Factores Humanos"],
  ["tripulación distraída por QRH perdió conciencia situacional durante remolque","Factores Humanos"],
  ["presión por salida puntual llevó a saltear verificación de carga peligrosa","Factores Humanos"],
  ["primer oficial completaba flujos de cabina y cruzó pista sin verificar clearance","Factores Humanos"],
  // ── NASA ASRS — Ground Damage reales ───────────────────────────────────
  ["pushback operator released brakes prematurely causing uncommanded aircraft movement","Ground Damage"],
  ["ramp agent handling dangerous goods sustained chemical burns from leaking parcel","Ground Damage"],
  ["bus blocked pushback path and nearly struck aircraft wing during departure","Ground Damage"],
  ["dangerous goods loaded after brake release due to on-time departure pressure","Ground Damage"],
  ["yellow hose sucked into left engine as aircraft parked at gate","Ground Damage"],
  ["aircraft overshot parking spot when automated parking system failed to command stop","Ground Damage"],
  ["jet blast from engine blew mechanic off maintenance stand during gate repositioning","Ground Damage"],
  ["two aircraft tails collided during pushback inadequately monitored by ground crew","Ground Damage"],
  ["deicing fluid on ramp caused chocks to slide allowing aircraft to roll backward","Ground Damage"],
  ["wingwalker absent aircraft wingtip struck catering truck during taxi in","Ground Damage"],
  ["agente de rampa lesionado al manipular carga peligrosa con pérdida de contenido","Ground Damage"],
  ["aeronave superó línea de estacionamiento por falla del sistema automático de guía","Ground Damage"],
  ["remolque desconectado rodó hacia aeronave causando daño en tren de nariz","Ground Damage"],
  ["pushback sin comunicación efectiva resultó en colisión de estabilizadores","Ground Damage"],
  ["personal de rampa no colocó calzos correctamente aeronave rodó en plataforma","Ground Damage"],
  // ── NASA ASRS — Incursión de Pista reales ──────────────────────────────
  ["student pilot crossed active runway in low visibility conditions without clearance","Incursión de Pista"],
  ["air carrier crew crossed runway hold short line in fog and drizzle","Incursión de Pista"],
  ["aircraft landed long and exited onto intersecting active runway","Incursión de Pista"],
  ["controller cleared aircraft for takeoff on runway occupied by airport vehicle","Incursión de Pista"],
  ["first officer crossed runway while completing cockpit flows during taxi","Incursión de Pista"],
  ["captain turned off taxi lights causing crew to taxi onto active runway at night","Incursión de Pista"],
  ["pilot distracted by smoke in cockpit inadvertently crossed active runway","Incursión de Pista"],
  ["three aircraft occupied runway simultaneously at non-towered airport","Incursión de Pista"],
  ["tripulación cruzó pista activa sin clearance de la torre durante rodaje nocturno","Incursión de Pista"],
  ["aeronave entró a pista en uso sin autorización por confusión de señalización","Incursión de Pista"],
  ["vehículo de plataforma ingresó a pista activa sin coordinación con torre","Incursión de Pista"],
  ["controlador olvidó vehículo en pista y autorizó despegue causando incursión","Incursión de Pista"],
  ["baja visibilidad y niebla causaron que tripulación cruzara línea de espera de pista","Incursión de Pista"],
  // ── NASA ASRS — TCAS RA reales ─────────────────────────────────────────
  ["TCAS showed near collision with law enforcement helicopters after departure","TCAS RA"],
  ["crew followed TCAS RA to climb and passed over helicopter by 100 feet","TCAS RA"],
  ["TCAS II traffic warning from aircraft behind on final approach at non-towered airport","TCAS RA"],
  ["tripulación recibió RA de TCAS en ascenso por conflicto con helicóptero no comunicado","TCAS RA"],
  ["aviso de tráfico TCAS en final por aeronave no informada en frecuencia CTAF","TCAS RA"],
  // ── NASA ASRS — Falla Técnica reales ───────────────────────────────────
  ["airspeed indication fluctuated from 40 to 300 knots due to ice on pitot probes","Falla Técnica"],
  ["violent flutter of flight controls during takeoff caused by ice inside control surfaces","Falla Técnica"],
  ["unreliable airspeed indication in IMC required manual pitch and power control","Falla Técnica"],
  ["indicación de velocidad aerodinámica no confiable por sondas pitot congeladas en IMC","Falla Técnica"],
  ["aleteo violento de superficies de control por hielo interno no detectado en inspección","Falla Técnica"],
  // ── NASA ASRS — Pérdida de Control reales ─────────────────────────────
  ["aircraft exceeded 45 degrees of bank during descending turn in IMC at night","Pérdida de Control"],
  ["airspeed decayed below Vref during disoriented turning maneuver requiring upset recovery","Pérdida de Control"],
  ["capitán desorientado en IMC nocturno alcanzó 45 grados de escora requiriendo recuperación","Pérdida de Control"],
  // ── NASA ASRS — CFIT / CFTT reales ───────────────────────────────────
  ["GPS jamming caused aircraft to navigate toward terrain controller issued heading to avoid","CFIT"],
  ["pilot intercepted VNAV bug instead of ILS glideslope descended toward terrain in low IMC","CFIT"],
  ["crew entered wrong altimeter setting descended 400 feet below assigned altitude toward terrain","CFIT"],
  ["wide-body aircraft received TERRAIN AHEAD warning during steep descent in mountainous area","CFIT"],
  ["aircraft descended below minimum vectoring altitude in IMC controller issued low altitude alert","CFIT"],
  ["crew set MDA in altitude preselect at FAF and received gear warning horn indicating terrain proximity","CFIT"],
  ["crew descended to MDA before FAF at night due to fatigue and get-home-itis","CFIT"],
  ["aeronave descendió por debajo de la MDA antes del FAF activando alerta de baja altitud","CFIT"],
  ["tripulación confundió ajuste altimétrico y descendió 500 pies por debajo de altitud asignada","CFIT"],
  ["aeronave en descenso no autorizado activó alerta MSAW del controlador por proximidad al terreno","CFIT"],
  ["piloto siguió bug incorrecto del FMS y descendió bajo mínima seguridad en IMC","CFIT"],
  ["tripulación aterrizó en aeropuerto equivocado por confusión visual en condiciones de neblina","CFIT"],
  ["aproximación al aeropuerto incorrecto en condiciones de visibilidad reducida alerta de baja altitud","CFIT"],
  ["aeronave en descenso visual impactó con terreno elevado por falta de conciencia situacional","CFIT"],
  ["vuelo controlado hacia el terreno por desorientación espacial en condiciones de baja visibilidad","CFIT"],
  ["pilot rushed runway change setup and mistook VSI bug for glideslope got low altitude alert","CFIT"],
  ["aircraft on visual approach flew into haze and began descending to wrong airport","CFIT"],
  ["controller missed terrain proximity until MSAW alert fired aircraft was below MVA","CFIT"],
  ["crew on RNAV approach descended through FAF altitude without crossing the fix","CFIT"],
  ["aeronave impactó terreno sin alerta GPWS por baja altitud y alta tasa de descenso","CFIT"],
  ["vuelo nocturno sin referencia visual impactó agua por confusión altimétrica","CFIT"],
  ["piloto confundió aeropuerto destino con aeropuerto cercano durante visual en neblina","CFIT"],
  ["CFIT recovery maneuver executed after TERRAIN AHEAD warning during vectoring below safe altitude","CFIT"],
  // ── NASA ASRS — Presurización reales ──────────────────────────────────
  ["cabin altitude warning horn activated while climbing through FL260 abnormal pressurization","Presurización"],
  ["pressurization loss during climb main air valves warning illuminated cabin altitude climbing","Presurización"],
  ["rapid decompression at cruise altitude crew donned oxygen masks and initiated emergency descent","Presurización"],
  ["cabin pressure climbing uncontrolled switched to standby mode and diverted to alternate","Presurización"],
  ["outflow valve stuck open caused cabin altitude to climb above 10000 feet","Presurización"],
  ["pressurization controller failure at FL350 crew declared emergency and descended to 10000 feet","Presurización"],
  ["aircraft still pressurized at gate flight attendants could not open cabin door","Presurización"],
  ["pérdida de presurización en crucero tripulación activó máscaras de oxígeno y descendió de emergencia","Presurización"],
  ["altitud de cabina superó 10000 pies por falla de válvula de salida en vuelo","Presurización"],
  ["descompresión rápida en FL380 tripulación realizó descenso de emergencia a FL100","Presurización"],
  ["cabina sin presurización por falla de compuerta tripulación y pasajeros en oxígeno de emergencia","Presurización"],
  ["warning de presurización de cabina activado en ascenso por squat switch congelado","Presurización"],
  ["falla del sistema de control de presurización tripulación desvió a aeropuerto alternativo","Presurización"],
  ["oxygen masks deployed in cabin after pressure altitude exceeded safe limits","Presurización"],
  ["crew failed to pressurize aircraft after maintenance check causing cabin altitude warning","Presurización"],
  ["pressurization pack failure required diversion crew used supplemental oxygen during descent","Presurización"],
  ["bleed air system anomaly caused pressurization to fail at high altitude","Presurización"],
  ["crew heard bang followed by rapid pressure change requiring immediate emergency descent","Presurización"],
  ["presión de cabina no controlada alcanzó altitud de 14000 pies activando sistema de oxígeno","Presurización"],
  ["falla de válvula de purga causó presurización irregular con advertencia de altitud de cabina","Presurización"],
  ["pasajeros experimentaron molestia en oídos y sangrado nasal por falla de presurización","Presurización"],
  ["tripulante de cabina notó presurización anormal e informó a piloto que inició descenso","Presurización"],
  // ── NASA ASRS — Smoke / Humo a Bordo reales ───────────────────────────
  ["electrical fire behind circuit breaker panel crew discharged fire extinguisher and declared emergency","Smoke / Humo a Bordo"],
  ["smoke filled cockpit from electrical short in instrument panel crew diverted and landed safely","Smoke / Humo a Bordo"],
  ["hydraulic fluid leak in air conditioning pack caused smoke and fumes in cabin","Smoke / Humo a Bordo"],
  ["APU smoke detected on ground crew evacuated passengers via slides","Smoke / Humo a Bordo"],
  ["fumes in cockpit from burned brake coil required crew to don oxygen masks","Smoke / Humo a Bordo"],
  ["cargo smoke warning activated crew performed emergency descent and diverted","Smoke / Humo a Bordo"],
  ["humo en cabina de pasajeros por cortocircuito en sistema de entretenimiento a bordo","Smoke / Humo a Bordo"],
  ["olor a quemado en cabina de vuelo tripulación se colocó máscaras y desvió vuelo","Smoke / Humo a Bordo"],
  ["humo visible en conductos de aire acondicionado pasajeros evacuados por toboganes","Smoke / Humo a Bordo"],
  ["incendio eléctrico en panel de disyuntores tripulación descargó extintor y aterrizó de emergencia","Smoke / Humo a Bordo"],
  ["fuego en motor número dos detectado por tripulante se ejecutó checklist de emergencia","Smoke / Humo a Bordo"],
  ["humo en bodega de carga tripulación declaró emergencia y realizó descenso de emergencia","Smoke / Humo a Bordo"],
  ["cabin crew reported smoke odor in aft galley crew declared emergency and diverted","Smoke / Humo a Bordo"],
  ["smoke from overheating wiring harness required immediate landing at nearest airport","Smoke / Humo a Bordo"],
  ["fumes from deicing fluid entered cabin through ventilation crew used oxygen masks","Smoke / Humo a Bordo"],
  ["passenger noticed smoke near overhead panel crew notified ATC and diverted","Smoke / Humo a Bordo"],
  ["burning smell in cockpit traced to avionics bay crew performed precautionary landing","Smoke / Humo a Bordo"],
  ["L-1011 cockpit electrical fire caused multiple system failures crew made emergency landing","Smoke / Humo a Bordo"],
  ["engine compartment fire warning activated crew shut down engine and landed at nearest airport","Smoke / Humo a Bordo"],
  ["cargo hold smoke indication during cruise required immediate diversion and emergency services","Smoke / Humo a Bordo"],
  // ── NASA ASRS — Fuel / Combustible reales ─────────────────────────────
  ["helicopter fuel exhaustion forced landing due to misread fuel gauge at private airfield","Fuel / Combustible"],
  ["GA aircraft fuel exhaustion after FBO failed to fuel tanks as requested","Fuel / Combustible"],
  ["cargo crew missed fuel transfer light low fuel warning and valve in wrong position","Fuel / Combustible"],
  ["engine flamed out on takeoff due to main fuel tank virtually empty from open valve","Fuel / Combustible"],
  ["mud dauber nests fouled PT2 probes causing abnormal engine pressure ratio readings","Fuel / Combustible"],
  ["fuel mismanagement crew disbelieved fuel gauge and departed with insufficient fuel","Fuel / Combustible"],
  ["agotamiento de combustible en vuelo tripulación realizó aterrizaje de emergencia en campo","Fuel / Combustible"],
  ["error de cálculo de combustible requirió desvío a aeropuerto alternativo antes de destino","Fuel / Combustible"],
  ["válvula de combustible abierta vació tanque principal causando falla de motor en despegue","Fuel / Combustible"],
  ["tripulación no verificó niveles de combustible con varilla y despegó con combustible insuficiente","Fuel / Combustible"],
  ["fuel starvation caused engine flameout during approach crew restarted engine and landed safely","Fuel / Combustible"],
  ["crew declared mayday due to minimum fuel state after holding pattern extended by ATC","Fuel / Combustible"],
  ["cross-feed valve improperly positioned caused fuel imbalance and engine anomaly during cruise","Fuel / Combustible"],
  ["combustible insuficiente en tanque derecho por error de abastecimiento causó apagado de motor","Fuel / Combustible"],
  ["aeronave aterrizó con reserva mínima de combustible por planificación incorrecta de vuelo","Fuel / Combustible"],
  ["piloto ignoró indicador de combustible bajo y continuó vuelo causando aterrizaje de emergencia","Fuel / Combustible"],
  ["falla del medidor de combustible llevó a tripulación a subestimar consumo real del vuelo","Fuel / Combustible"],
  ["tanque de combustible contaminado con agua causó falla de motor durante vuelo en crucero","Fuel / Combustible"],
  ["derrame de combustible en ala durante abastecimiento requirió inspección antes de vuelo","Fuel / Combustible"],
  ["insect nest in fuel vent caused fuel starvation requiring emergency landing in field","Fuel / Combustible"],
  ["crew landed with less than minimum required fuel reserve due to unexpected headwinds","Fuel / Combustible"],
  // ── NASA ASRS — FOD reales ────────────────────────────────────────────
  ["C172 pilot dropped cowl plugs on active runway during initial climb failed to notify tower","FOD"],
  ["cowl plugs found sitting on runway centerline near 500 foot marker after departure","FOD"],
  ["ramp vehicle left tool on taxiway aircraft ingested object causing engine damage","FOD"],
  ["runway inspection found metal debris from previous aircraft operation causing tire damage","FOD"],
  ["debris on runway caused blown tire during takeoff roll requiring rejected takeoff","FOD"],
  ["objeto extraño en pista detectado por piloto en rodaje se notificó a la torre","FOD"],
  ["restos de aeronave anterior en pista causaron daño en tren de aterrizaje al aterrizar","FOD"],
  ["herramienta de mantenimiento olvidada en zona de rodaje causó daño en motores de turbina","FOD"],
  ["plástico de embalaje en pista ingerido por motor causó daño en compresor","FOD"],
  ["bird remains on runway caused FOD damage to engine inlet during takeoff roll","FOD"],
  ["FOD encontrado en pista por equipo de inspección causó cierre temporal de operaciones","FOD"],
  ["foreign object ingestion by engine detected after departure crew declared emergency","FOD"],
  ["maintenance left cowling panel on ramp aircraft ran over it causing structural damage","FOD"],
  ["debris blown from construction area onto active taxiway reported by departing aircraft","FOD"],
  ["hailstones on ramp surface ingested by engine causing damage to fan blades","FOD"],
  ["piloto olvidó remover tapones del motor y los ingirió en el despegue","FOD"],
  ["tapas de pitot no removidas antes del vuelo causaron indicaciones de velocidad incorrectas","FOD"],
  ["material de construcción adyacente a la pista migró al área de movimiento por viento","FOD"],
  ["foreign object damage to propeller detected after landing investigation found runway debris","FOD"],
  ["loose pavement fragment on runway caused tire burst and rejected takeoff at high speed","FOD"],
  ["FOD inspection found multiple metal fragments after maintenance work near active runway","FOD"],
  // ── NASA ASRS — Emergencia Médica reales ──────────────────────────────
  ["first officer experienced sudden food poisoning during cruise captain handled controls alone","Emergencia Médica"],
  ["passenger medical emergency required diversion crew used supplemental oxygen and EMK","Emergencia Médica"],
  ["flight attendant collapsed mid-flight doctor on board assisted crew diverted to nearest airport","Emergencia Médica"],
  ["passenger suffered cardiac arrest crew performed CPR with AED and declared emergency","Emergencia Médica"],
  ["crew diverted after using EMK oxygen bottles and forgot to restock before continuing","Emergencia Médica"],
  ["pasajero sufrió convulsiones durante vuelo médico a bordo asistió hasta el aterrizaje","Emergencia Médica"],
  ["tripulante de cabina se desmayó en vuelo piloto solicitó atención médica prioritaria en tierra","Emergencia Médica"],
  ["pasajero con dolor de pecho severo desvió vuelo a aeropuerto con servicios médicos","Emergencia Médica"],
  ["piloto declaró emergencia médica por incapacitación del copiloto aterrizó sin asistencia","Emergencia Médica"],
  ["emergencia médica de pasajero requirió desvío y consumo de todo el oxígeno médico disponible","Emergencia Médica"],
  ["passenger lost consciousness at cruising altitude crew requested priority landing","Emergencia Médica"],
  ["crew declared medical emergency after passenger suffered severe allergic reaction inflight","Emergencia Médica"],
  ["flight attendant suffered incapacitation requiring crew to assist passengers alone","Emergencia Médica"],
  ["passenger with respiratory distress required supplemental oxygen entire flight crew diverted","Emergencia Médica"],
  ["pilot became ill inflight copilot assumed full control and declared emergency landing","Emergencia Médica"],
  ["reacción alérgica severa de pasajero requirió uso del kit de emergencia médica a bordo","Emergencia Médica"],
  ["pasajero embarazada entró en trabajo de parto durante vuelo médico a bordo asistió parto","Emergencia Médica"],
  ["tripulante de vuelo incapacitado por intoxicación alimentaria piloto aterrizó sin copiloto activo","Emergencia Médica"],
  ["pérdida de conciencia de pasajero activó protocolo de emergencia médica a bordo","Emergencia Médica"],
  ["desmayo de pasajero con antecedentes cardíacos requirió desvío urgente y coordinación médica en tierra","Emergencia Médica"],
  // ── NASA ASRS — Pérdida de Control adicionales ─────────────────────────
  ["crew encountered severe turbulence with uncommanded climb declared emergency unable to control altitude","Pérdida de Control"],
  ["aircraft entered stall during go-around crew applied full power and recovered at low altitude","Pérdida de Control"],
  ["pilot lost control in IMC after spatial disorientation aircraft exceeded Vmo before recovery","Pérdida de Control"],
  ["aeronave perdió control en condiciones de turbulencia severa tripulación realizó recuperación de maniobra inusual","Pérdida de Control"],
  ["pérdida de control durante la aproximación por cizalladura de viento tripulación ejecutó go-around","Pérdida de Control"],
  ["turbulencia extrema causó desenganche del piloto automático tripulación tomó control manual","Pérdida de Control"],
  ["aircraft rolled beyond 60 degrees bank in IMC wake turbulence encounter at cruise","Pérdida de Control"],
  ["stall warning activated during final approach crew performed upset recovery and go-around","Pérdida de Control"],
  ["aeronave en pérdida de sustentación durante viraje pronunciado tripulación recuperó control a baja altitud","Pérdida de Control"],
  ["UPRT techniques applied after autopilot disconnect and airspeed anomaly in turbulent conditions","Pérdida de Control"],
  ["pitch excursion beyond normal envelope during severe turbulence required crew to disconnect automation","Pérdida de Control"],
  ["tailplane stall caused nose-down pitch upset on approach requiring aggressive recovery inputs","Pérdida de Control"],
  // ── NASA ASRS — Demora Operacional adicionales ─────────────────────────
  ["departure delayed three hours due to maintenance work on hydraulic system","Demora Operacional"],
  ["flight delayed due to crew rest requirement exceeded after unexpected diversion","Demora Operacional"],
  ["gate return required after pressurization fault discovered during initial climb causing two hour delay","Demora Operacional"],
  ["vuelo demorado por condiciones meteorológicas adversas en aeropuerto de destino","Demora Operacional"],
  ["demora de cuatro horas por falta de tripulación de relevo disponible en escala","Demora Operacional"],
  ["retraso por congestión en pista de aterrizaje y cierre temporal por inspección de FOD","Demora Operacional"],
  ["aircraft returned to gate after smoke indication crew performed troubleshooting causing long delay","Demora Operacional"],
  ["delay caused by late connecting passengers requiring luggage offload from hold","Demora Operacional"],
  ["vuelo retrasado por paperwork incompleto de carga peligrosa detectado en último momento","Demora Operacional"],
  ["demora por falla de puerta de embarque que no se acopló correctamente a la aeronave","Demora Operacional"],
  ["flight held for two hours at gate due to ground stop issued by ATC for destination airport","Demora Operacional"],
  ["delayed departure due to weight and balance recalculation after last minute cargo changes","Demora Operacional"],
  // ── NASA ASRS — GPWS adicionales ──────────────────────────────────────
  ["GPWS terrain ahead warning activated during approach in mountainous terrain crew executed escape maneuver","GPWS"],
  ["GPWS sink rate warning triggered during unstabilized approach crew performed immediate go-around","GPWS"],
  ["GPWS pull up warning activated crew applied maximum thrust and climb to escape terrain","GPWS"],
  ["enhanced GPWS caution alert during descent in mountainous area required immediate altitude correction","GPWS"],
  ["GPWS too low terrain warning on visual approach in reduced visibility crew executed go-around","GPWS"],
  ["alerta GPWS de terreno adelante activada por descenso prematuro en aproximación instrumental","GPWS"],
  ["advertencia de tasa de descenso excesiva GPWS activada en final comandante ejecutó go-around","GPWS"],
  ["alerta pull-up del GPWS disparada en descenso en zona montañosa tripulación aplicó TOGA","GPWS"],
  ["sistema GPWS activado por flaps no configurados durante aproximación visual nocturna","GPWS"],
  ["GPWS terrain caution fired due to late gear extension on non-precision approach","GPWS"],
  ["crew ignored initial GPWS caution and received pull-up warning requiring full escape maneuver","GPWS"],
  ["GPWS alert during ILS approach due to incorrect QNH entered crew climbed and recycled approach","GPWS"],
  ["EGPWS generated caution during circling approach to lower minima in mountainous terrain","GPWS"],
  // ── NASA ASRS — Unstable Approach adicionales ─────────────────────────
  ["flight crew executed go-around after unstable approach with high speed and wrong configuration","Unstable Approach"],
  ["captain continued approach despite first officer calling unstable resulting in hard landing","Unstable Approach"],
  ["windshear warning on approach at 1000 feet required immediate go-around execution","Unstable Approach"],
  ["aircraft was high and fast on final crew did not initiate go-around and overran runway","Unstable Approach"],
  ["landing was preceded by excessive descent rate crew should have gone around per SOP","Unstable Approach"],
  ["aproximación inestable por viento cruzado fuerte comandante ejecutó go-around a 500 pies","Unstable Approach"],
  ["tripulación continuó aproximación inestable por presión de puntualidad y dañó tren de nariz","Unstable Approach"],
  ["aeronave alta y rápida en final no realizó go-around y excedió zona de aterrizaje","Unstable Approach"],
  ["alerta de cizalladura de viento activada en aproximación tripulación ejecutó procedimiento TOGA","Unstable Approach"],
  ["CRM failure allowed unstabilized approach to continue below 500 feet against SOPs","Unstable Approach"],
  ["speed above Vref plus 20 at 500 feet crew failed to initiate mandatory go-around","Unstable Approach"],
  ["aproximación inestable en condiciones de lluvia intensa comandante tardó en ejecutar go-around","Unstable Approach"],
  // ── NASA ASRS — Turbulencia adicionales ───────────────────────────────
  ["severe turbulence at FL350 caused multiple passenger injuries seatbelt sign was off","Turbulencia"],
  ["clear air turbulence at cruise altitude caused sudden aircraft upset two attendants fell","Turbulencia"],
  ["microburst on final caused windshear crew executed go-around and declared emergency","Turbulencia"],
  ["wake turbulence from preceding heavy aircraft caused violent roll on approach","Turbulencia"],
  ["mountain wave turbulence at FL290 caused rapid altitude deviation of 2000 feet","Turbulencia"],
  ["turbulencia severa en crucero en zona de tormentas tres pasajeros lesionados sin cinturón","Turbulencia"],
  ["turbulencia de estela al seguir aeronave pesada en final causó pérdida momentánea de control","Turbulencia"],
  ["turbulencia en capas claras sorprendió a tripulación sin advertencia meteorológica previa","Turbulencia"],
  ["severa turbulencia en ascenso por onda de montaña tripulante de cabina resultó herida","Turbulencia"],
  ["convective turbulence caused structural inspection after exceeding aircraft load limits","Turbulencia"],
  ["pilot encountered unexpected severe turbulence in dissipating thunderstorm cell during descent","Turbulencia"],
  ["tripulación encontró turbulencia de estela de aeronave pesada causando cabeceo severo","Turbulencia"],
  // ── Turbulencia — EN/ES expansión ───────────────────────────────────────
  ["severe turbulence over the Atlantic injured two passengers","Turbulencia"],
  ["extreme turbulence at cruise altitude seatbelt sign on","Turbulencia"],
  ["mountain wave turbulence caused aircraft to lose 500ft","Turbulencia"],
  ["CAT encounter flight level 350 severe injuries reported","Turbulencia"],
  ["wake turbulence from preceding heavy on approach","Turbulencia"],
  ["moderate chop in cruise fasten seatbelt sign activated","Turbulencia"],
  ["turbulencia severa en crucero dos pasajeros lesionados leve","Turbulencia"],
  ["turbulencia de estela del tráfico precedente afectó el aterrizaje","Turbulencia"],
  ["turbulencia moderada en zona de tormentas cinturo abrochado","Turbulencia"],
  ["pasajeros golpearon el techo por turbulencia inesperada severa","Turbulencia"],
  // ── Seguridad Aeroportuaria — EN/ES expansión ────────────────────────────
  ["unattended bag found at terminal entrance security notified","Seguridad Aeroportuaria"],
  ["suspicious package reported near boarding gate evacuation","Seguridad Aeroportuaria"],
  ["unauthorized person attempted to access airside area","Seguridad Aeroportuaria"],
  ["passenger stolen luggage reported in baggage claim area","Seguridad Aeroportuaria"],
  ["stowaway found in cargo hold aircraft grounded","Seguridad Aeroportuaria"],
  ["knife found in carry-on during screening process","Seguridad Aeroportuaria"],
  ["intruder on the apron security breach perimeter fence","Seguridad Aeroportuaria"],
  ["threat received via phone bomb threat terminal evacuated","Seguridad Aeroportuaria"],
  ["suspicious individual following passengers in departure hall","Seguridad Aeroportuaria"],
  ["bag left unattended at check-in counter for 30 minutes","Seguridad Aeroportuaria"],
  ["persona no autorizada en zona de rampa fue detenida","Seguridad Aeroportuaria"],
  ["amenaza telefónica de bomba en terminal norte evacuación activada","Seguridad Aeroportuaria"],
  ["robo de equipaje en la sala de reclamo pasajero denunció","Seguridad Aeroportuaria"],
  ["objeto cortante encontrado en el control de seguridad","Seguridad Aeroportuaria"],
  ["polizón hallado en bodega de aeronave al llegar destino","Seguridad Aeroportuaria"],
  // ── Incursión de Pista — EN/ES expansión ────────────────────────────────
  ["aircraft crossed active runway without clearance from ATC","Incursión de Pista"],
  ["vehicle entered runway 10L without authorization","Incursión de Pista"],
  ["runway incursion category C aircraft on final had to go around","Incursión de Pista"],
  ["pilot misread taxi instruction and crossed hold short point","Incursión de Pista"],
  ["ground vehicle incursion on active runway at night","Incursión de Pista"],
  ["wrong runway entry by aircraft complex intersection at night","Incursión de Pista"],
  ["incursión de pista un vehículo cruzó sin autorización","Incursión de Pista"],
  ["aeronave ingresó a pista activa sin autorización del control","Incursión de Pista"],
  ["tripulación cruzó punto de espera de pista sin clearance","Incursión de Pista"],
  ["vehículo de mantenimiento en pista activa tráfico en final","Incursión de Pista"],
  // ── CFIT — EN/ES expansión ───────────────────────────────────────────────
  ["controlled flight into terrain near mountain avoided last second","CFIT"],
  ["aircraft descended below minimum safe altitude in IMC","CFIT"],
  ["CFIT precursor non-precision approach below MDA in VMC","CFIT"],
  ["hit terrain while fully controllable poor situational awareness","CFIT"],
  ["descenso no autorizado por debajo de la altitud de seguridad en montaña","CFIT"],
  ["aeronave descendió bajo MDA en niebla sin pista visible","CFIT"],
  ["impacto con terreno en condiciones de vuelo controlado zona montañosa","CFIT"],
  // ── Emergencia Médica — EN/ES expansión ─────────────────────────────────
  ["passenger cardiac arrest in flight emergency landing diverted","Emergencia Médica"],
  ["unconscious passenger in economy class doctor on board","Emergencia Médica"],
  ["in-flight medical emergency diabetic shock passenger responded","Emergencia Médica"],
  ["passenger seizure mid-flight doctor requested priority landing","Emergencia Médica"],
  ["crew member ill in flight copilot assumed duties","Emergencia Médica"],
  ["anaphylactic shock onboard epinephrine administered divert","Emergencia Médica"],
  ["pasajero inconsciente paro cardíaco médico a bordo aterrizaje urgente","Emergencia Médica"],
  ["emergencia médica pasajero convulsionó piloto solicitó prioridad","Emergencia Médica"],
  ["tripulante enfermo en vuelo asumió copiloto aterrizaje precautorio","Emergencia Médica"],
  ["hipoglucemia severa de pasajero respondió al azúcar administrado","Emergencia Médica"],
  // ── Smoke/Humo a Bordo — EN/ES expansión ────────────────────────────────
  ["smoke in the cockpit oxygen masks on declared emergency","Smoke / Humo a Bordo"],
  ["burning smell in cabin crew investigated no smoke source found","Smoke / Humo a Bordo"],
  ["lavatory smoke detector activated crew checked no fire","Smoke / Humo a Bordo"],
  ["fumes in the cabin suspected bleed air contamination","Smoke / Humo a Bordo"],
  ["smoke from avionics bay fire extinguisher deployed divert","Smoke / Humo a Bordo"],
  ["humo en cabina olor a quemado tripulación activó protocolo","Smoke / Humo a Bordo"],
  ["detector de humo del baño activó revisión sin focos de incendio","Smoke / Humo a Bordo"],
  ["olor a humo en cabina de vuelo uso de oxígeno emergencia declarada","Smoke / Humo a Bordo"],
  ["fugas de aire de sangría con olor a aceite quemado en cabina","Smoke / Humo a Bordo"],
  // ── Pérdida de Control — EN/ES expansión ────────────────────────────────
  ["loss of control recovered at low altitude near stall","Pérdida de Control"],
  ["aircraft entered unusual attitude crew recovered manually","Pérdida de Control"],
  ["stall warning activated at low altitude crew reacted late","Pérdida de Control"],
  ["upset event in turbulence 60-degree bank recovered","Pérdida de Control"],
  ["aerodynamic stall inadvertent during training evolution recovered","Pérdida de Control"],
  ["pérdida de control recuperada a baja altura alarma de pérdida activó","Pérdida de Control"],
  ["entrada en actitud inusual tripulación recuperó manualmente","Pérdida de Control"],
  ["alarma de pérdida de sustentación a baja altura recuperaron tarde","Pérdida de Control"],
  // ── Presurización — EN/ES expansión ─────────────────────────────────────
  ["rapid decompression masks dropped oxygen deployed","Presurización"],
  ["cabin altitude exceeded 10000ft masks deployed emergency descent","Presurización"],
  ["pressurization failure during climb diverted to lower altitude","Presurización"],
  ["outflow valve malfunction cabin pressure uncontrolled","Presurización"],
  ["descompresión rápida máscaras cayeron descenso de emergencia","Presurización"],
  ["altitud de cabina superó 10000 pies descenso urgente ejecutado","Presurización"],
  ["falla de presurización en subida desvío a aeropuerto alternado","Presurización"],
  ["válvula de salida bloqueada presión de cabina incontrolada","Presurización"],
  // ── Fuel/Combustible — EN/ES expansión ──────────────────────────────────
  ["fuel leak from left wing trailing edge discovered on ground","Fuel / Combustible"],
  ["fuel imbalance 2000 kg between tanks crossfeed required","Fuel / Combustible"],
  ["declared minimum fuel priority landing approved by ATC","Fuel / Combustible"],
  ["fuel exhaustion risk declared mayday diverted immediately","Fuel / Combustible"],
  ["incorrect fueling quantity error departure fuel too low","Fuel / Combustible"],
  ["pérdida de combustible en ala derecha detectada en tierra","Fuel / Combustible"],
  ["desequilibrio de combustible 1500 kg cruce de alimentación","Fuel / Combustible"],
  ["combustible mínimo declarado prioridad aterrizaje ATC","Fuel / Combustible"],
  ["carga de combustible errónea vuelo con menos combustible necesario","Fuel / Combustible"],
  // ── FOD — EN/ES expansión ───────────────────────────────────────────────
  ["foreign object debris on runway bird carcass reported","FOD"],
  ["tool found on apron after maintenance missing from kit","FOD"],
  ["debris on taxiway alpha ingestion risk reported to operations","FOD"],
  ["piece of metal found on runway 28L inspected before ops","FOD"],
  ["cone left on apron after pushback FOD hazard reported","FOD"],
  ["objeto extraño en pista fragmento metálico peligro de ingestión","FOD"],
  ["herramienta de mantenimiento encontrada en plataforma sin marcar","FOD"],
  ["resto de ave en pista reportado a ATC limpieza realizada","FOD"],
  ["escombros en calle de rodaje riesgo de ingestión notificado","FOD"],
  // ── Interferencia Ilícita — EN/ES expansión ──────────────────────────────
  ["hijack attempt crew activated squawk 7500","Interferencia Ilícita"],
  ["passenger threatened crew with weapon emergency declared","Interferencia Ilícita"],
  ["unruly passenger restrained by crew interfered with flight ops","Interferencia Ilícita"],
  ["bomb threat note found in aircraft lavatory","Interferencia Ilícita"],
  ["passenger attempted to open aircraft door in flight restrained","Interferencia Ilícita"],
  ["intento de secuestro código 7500 activado tripulación respondió","Interferencia Ilícita"],
  ["pasajero violento amenazó tripulación con objeto contundente","Interferencia Ilícita"],
  ["amenaza de bomba escrita encontrada en baño de aeronave","Interferencia Ilícita"],
  ["pasajero intentó abrir puerta en vuelo fue inmovilizado","Interferencia Ilícita"],
  // ── Demora Operacional — EN/ES expansión ─────────────────────────────────
  ["flight delayed 3 hours due to late crew positioning","Demora Operacional"],
  ["aircraft swap required technical issue caused 2 hour delay","Demora Operacional"],
  ["ATC holding pattern burned extra fuel delayed arrival","Demora Operacional"],
  ["late baggage loading caused 45-minute departure delay","Demora Operacional"],
  ["ground stop issued weather delay all departures held","Demora Operacional"],
  ["vuelo demorado 3 horas por atraso en el posicionamiento de tripulación","Demora Operacional"],
  ["cambio de aeronave por falla técnica demora de 2 horas","Demora Operacional"],
  ["espera en patrón por congestión de tráfico ATC demora en destino","Demora Operacional"],
  ["carga de equipaje tardía demoró la salida 40 minutos","Demora Operacional"],
  ["slot ATC retrasado por congestión en espacio aéreo demora 35 minutos","Demora Operacional"],
  ["pasajero enfermo en gate demoró embarque y salida del vuelo","Demora Operacional"],
  ["demora por inspección adicional de seguridad solicitada por autoridad aeroportuaria","Demora Operacional"],
  ["retraso en devolución de documentación de despacho ocasionó demora de 28 minutos","Demora Operacional"],
  // Smoke / Humo a Bordo
  ["acrid electrical smell reported in cabin crew notified captain smoke checklist executed","Smoke / Humo a Bordo"],
  // TCAS RA
  ["TCAS resolution advisory climb issued crew complied traffic separation restored","TCAS RA"],
  ["traffic alert and collision avoidance system commanded descend crew executed maneuver","TCAS RA"],
  ["TCAS RA triggered during cruise near miss with opposite direction traffic","TCAS RA"],
  ["aviso TCAS descend ejecutado tripulación separación vertical restaurada radar confirma","TCAS RA"],
  ["resolución TCAS monitor tráfico cruzado nivel de vuelo invasión espacio aéreo restringido","TCAS RA"],
  // Bird Strike
  ["ingested bird in engine number two at rotation engine vibration increase power reduced","Bird Strike"],
  ["bird strike windshield impact during approach blood feathers on nose radome","Bird Strike"],
  ["multiple bird ingestion both engines altitude 800 feet emergency declared landed safely","Bird Strike"],
  ["golpe de ave en tren de aterrizaje durante rodaje inspección post vuelo revela daño plumaje","Bird Strike"],
  ["bandada de aves en área de pista en despegue impacto en borde de ataque confirmado","Bird Strike"],
  // Interferencia Ilícita
  ["pasajero amenazó a tripulación con objeto punzante protocolo hijack activado","Interferencia Ilícita"],
  ["unauthorized access to flight deck attempted by passenger restrained by crew","Interferencia Ilícita"],
  ["bomb threat received on ground aircraft evacuated explosive ordnance disposal called","Interferencia Ilícita"],
  ["laser pointer directed at aircraft on approach temporary pilot vision impairment reported","Interferencia Ilícita"],
  ["amenaza de bomba anónima por llamada telefónica aeronave evacuada en plataforma","Interferencia Ilícita"],
  ["pasajero perturbador intentó abrir puerta de salida en vuelo inmovilizado por tripulación","Interferencia Ilícita"],
  // Pérdida de Control
  ["aircraft entered unusual attitude during turbulence autopilot disconnected crew recovered manually","Pérdida de Control"],
  ["loss of control upset recovery training activated roll exceedance 47 degrees bank angle","Pérdida de Control"],
  ["stall warning stick shaker activated on approach crew applied TOGA recovered altitude 300ft","Pérdida de Control"],
  ["pérdida de sustentación en aproximación alarma stick pusher activada recuperación con potencia","Pérdida de Control"],
  ["entrada en espiral descendente por desorientación espacial instrumentos contradictorios","Pérdida de Control"],
  ["overcorrection after windshear encounter aircraft exceeded structural limit g-load FOQA alert","Pérdida de Control"],
  ["aeronave excedió ángulo de asiento positivo durante despegue tail strike casi confirmado","Pérdida de Control"],
  // Runway Excursion
  ["aircraft departed runway surface during landing on contaminated runway with standing water","Runway Excursion"],
  ["runway excursion departure braking action poor aircraft stopped in grass arrest area","Runway Excursion"],
  ["excursión lateral en aterrizaje pista mojada viento cruzado aeronave detuvo en franja seguridad","Runway Excursion"],
  ["high speed rejected takeoff brake failure aircraft overran end of runway no injuries","Runway Excursion"],
  ["salida de pista durante despegue abortado distancia remanente insuficiente frenado inefectivo","Runway Excursion"],
  ["tailwind landing long flare touchdown beyond aiming point runway overrun arrestor bed activated","Runway Excursion"],
  ["excursión de pista en aterrizaje nocturno lluvia visibilidad reducida hydroplaning reportado","Runway Excursion"],
  ["aircraft veered off centerline during takeoff roll crosswind exceeding demonstrated limit","Runway Excursion"],
  // Hard Landing
  ["hard landing g-load exceeded structural limit maintenance inspection required","Hard Landing"],
  ["tasa de descenso 900 fpm en toque QAR registra excedencia mantenimiento activado","Hard Landing"],
  ["bounced landing crew went around second approach normal hard landing on first attempt","Hard Landing"],
  ["windshear encounter on short final caused hard touchdown g-limit exceeded FOQA flag","Hard Landing"],
  ["aterrizaje brusco en condiciones IMC tripulación reporta golpe fuerte inspección estructural","Hard Landing"],
  ["copilot flying first officer hard landing 780 fpm exceeded company limit training event triggered","Hard Landing"],
  ["microburst encounter approach caused sudden rate of descent increase hard contact runway","Hard Landing"],
  ["aterrizaje duro con rafagas QAR supera 2.0g inspección estructural programada compañía","Hard Landing"],
  ["long flare float excess speed touchdown zone overrun late braking hard landing sequence","Hard Landing"],
  ["rebote en aterrizaje segundo toque con tasa alta tripulación reporta golpe en cabina de vuelo","Hard Landing"],
  // Conducta inapropiada de tripulación → Factores Humanos
  ["cabin crew denunciada por contacto físico inapropiado con pasajero durante vuelo","Factores Humanos"],
  ["tripulante de cabina acusado de tocar a pasajero de forma inapropiada","Factores Humanos"],
  ["azafata denunciada por conducta inapropiada hacia pasajero en vuelo internacional","Factores Humanos"],
  ["pasajero presentó denuncia contra sobrecargo por contacto físico no consentido","Factores Humanos"],
  ["cabin crew reported for inappropriate behavior toward passenger flight attendant disciplined","Factores Humanos"],
  ["flight attendant complaint inappropriate physical contact passenger report filed","Factores Humanos"],
  ["crew member accused of misconduct toward passenger during flight","Factores Humanos"],
  ["tripulante de cabina reprendido por conducta inapropiada hacia menor a bordo","Factores Humanos"],
  ["cabin crew fue violada por el copiloto durante vuelo denuncia penal activada","Factores Humanos"],
  ["copiloto abusó sexualmente de azafata conducta gravemente inapropiada de tripulante","Factores Humanos"],
  ["tripulante agredió sexualmente a miembro de cabina durante vuelo internacional","Factores Humanos"],
  ["piloto acosó y violó a tripulante de cabina falla grave de conducta operacional","Factores Humanos"],
  ["sexual assault by first officer against cabin crew member crew misconduct sev5","Factores Humanos"],
  // ── METEOROLOGÍA ADVERSA / LVO ──────────────────────────────────────────
  ["niebla densa en pista no se ve ni la mano no quieren cerrar el aeropuerto","Meteorología Adversa"],
  ["baja visibilidad por niebla espesa impidió aproximación aeropuerto no cerró","Meteorología Adversa"],
  ["visibilidad inferior al mínimo CAT I aeropuerto continuó operando sin cerrar","Meteorología Adversa"],
  ["engelamiento en aeronave durante rodaje tratamiento de-icing solicitado en plataforma","Meteorología Adversa"],
  ["pista helada por lluvia congelante operaciones suspendidas temporalmente","Meteorología Adversa"],
  ["niebla densa RVR por debajo de mínimos aproximación CAT III activada","Meteorología Adversa"],
  ["tormenta eléctrica sobre el aeródromo rayos en pista operaciones detenidas 40 minutos","Meteorología Adversa"],
  ["desvío por meteorología adversa en destino alternativa declarada por mal tiempo","Meteorología Adversa"],
  ["presión operacional para despegar bajo condiciones IMC límite despachador insistió","Meteorología Adversa"],
  ["viento cruzado excedió límite máximo operacional aeronave tuvo que esperar 30 minutos","Meteorología Adversa"],
  ["nieve en pista limpieza solicitada demora en sweeping operaciones LVO activas","Meteorología Adversa"],
  ["visibilidad cero en pista 20 aeropuerto no activó procedimientos LVO tripulación reporta","Meteorología Adversa"],
  ["deicing insuficiente aeronave despachada con hielo residual en superficies de control","Meteorología Adversa"],
  ["pista anegada por lluvia intensa acumulación de agua hidroplaning probable","Meteorología Adversa"],
  ["espacio aéreo no cerrado pese a condiciones por debajo del mínimo publicado","Meteorología Adversa"],
  ["lluvia helada en ruta formación de hielo inesperada activación anti-ice tardía","Meteorología Adversa"],
  ["granizo en aeródromo aeronave en plataforma recibió impactos inspección requerida","Meteorología Adversa"],
  ["condiciones IMC en destino alternativa sin combustible suficiente decisión de continuar","Meteorología Adversa"],
  ["banco de niebla repentino redujo visibilidad a 50m aeronave en corto final","Meteorología Adversa"],
  ["viento cruzado reportado 35kt límite operacional 25kt despacho aprobado igual","Meteorología Adversa"],
  ["dense fog runway zero visibility airport not closed operations continued","Meteorología Adversa"],
  ["low visibility operations cat iii approach rvr below minimums reported","Meteorología Adversa"],
  ["ground icing deicing fluid contaminated surfaces aircraft dispatched with residual ice","Meteorología Adversa"],
  ["runway contaminated snow sweeping incomplete operations resumed early","Meteorología Adversa"],
  ["freezing rain in flight unexpected icing encounter anti-ice system activated late","Meteorología Adversa"],
  ["crosswind exceeded published limit dispatch approved flight continued","Meteorología Adversa"],
  ["thunderstorm over aerodrome lightning strikes operations halted ground stop issued","Meteorología Adversa"],
  ["weather divert destination below minimums alternate declared fuel critical","Meteorología Adversa"],
  ["pressure to operate below meteorological minimums dispatcher insisted continue","Meteorología Adversa"],
  ["black ice runway surface undetected braking action nil reported after landing","Meteorología Adversa"],

  // ── MERCANCÍAS PELIGROSAS (30) ────────────────────────────────────────────
  ["pasajero llevaba baterías de litio no declaradas en bodega potencial incendio","Mercancías Peligrosas"],
  ["batería de litio no declarada encontrada en equipaje de bodega riesgo de incendio","Mercancías Peligrosas"],
  ["cargamento de mercancías peligrosas clase 9 mal etiquetado detectado en plataforma","Mercancías Peligrosas"],
  ["material radioactivo transportado sin declaración DGR documentación incompleta","Mercancías Peligrosas"],
  ["mercancía peligrosa clase 3 inflamable cargada sin documentación correcta IATA DGR","Mercancías Peligrosas"],
  ["derrame de sustancia corrosiva en bodega durante vuelo mercancía peligrosa no declarada","Mercancías Peligrosas"],
  ["pasajero traía aerosoles inflamables sin declarar en equipaje de cabina","Mercancías Peligrosas"],
  ["contenedor dañado con material peligroso descubierto antes del vuelo en plataforma","Mercancías Peligrosas"],
  ["embalaje deficiente de mercancía peligrosa clase 8 corrosivo riesgo de fuga","Mercancías Peligrosas"],
  ["carga de oxígeno comprimido sin documentación DGR correcta detectada en rampa","Mercancías Peligrosas"],
  ["nitrato de amonio transportado sin clasificación correcta clase 5 oxidante","Mercancías Peligrosas"],
  ["pirotecnia no declarada en equipaje de pasajero descubierta en revisión de bodega","Mercancías Peligrosas"],
  ["hazmat no declarado en manifiesto de carga embarque clase 3 líquido inflamable","Mercancías Peligrosas"],
  ["personal de carga no capacitado DGR manipuló incorrectamente mercancía peligrosa clase 6","Mercancías Peligrosas"],
  ["baterías de ion de litio en cantidad que excede límites permitidos por IATA DGR","Mercancías Peligrosas"],
  ["medicina refrigerada con hielo seco transportada sin declaración CO2 sólido clase 9","Mercancías Peligrosas"],
  ["pasajero llevó pistola de aire comprimido sin declarar gas comprimido mercancía peligrosa","Mercancías Peligrosas"],
  ["undeclared lithium battery in checked baggage found during security screening cargo","Mercancías Peligrosas"],
  ["dangerous goods class 3 flammable loaded without proper DGR documentation shipper","Mercancías Peligrosas"],
  ["hazmat spill in cargo hold corrosive substance undeclared dangerous goods","Mercancías Peligrosas"],
  ["mercury in passenger baggage undeclared hazardous material class 8","Mercancías Peligrosas"],
  ["oxidizing agent improperly packed class 5 found on ramp before loading","Mercancías Peligrosas"],
  ["radioactive package without proper shielding documentation iata dangerous goods","Mercancías Peligrosas"],
  ["carga peligrosa etiquetada incorrectamente como general cargo detectada en rampeo","Mercancías Peligrosas"],
  ["declaración del expedidor incompleta para material peligroso clase 9 baterías","Mercancías Peligrosas"],
  ["chemical found in passenger baggage undeclared hazardous material bleach acetone","Mercancías Peligrosas"],
  ["cargamento de gas comprimido sin documentación DGR válida cylinders undeclared","Mercancías Peligrosas"],
  ["paint cans loaded undeclared flammable class 3 dangerous goods without declaration","Mercancías Peligrosas"],
  ["explosivos de señalización marítima en equipaje de pasajero detectados en control","Mercancías Peligrosas"],
  ["mercancía peligrosa despachada en vuelo de pasajeros sin aprobación operacional previa","Mercancías Peligrosas"],
  // ── INCIDENCIA ATC (30) ───────────────────────────────────────────────────
  ["controlador aéreo dio instrucción de descender a nivel ya ocupado por otra aeronave","Incidencia ATC"],
  ["atc autorizó dos aeronaves al mismo nivel de vuelo simultáneamente separación perdida","Incidencia ATC"],
  ["tripulación recibió instrucción de pista incorrecta autorizaron aterrizar en pista cerrada","Incidencia ATC"],
  ["controlador autorizó despegue cuando había aeronave en corto final incidente de pista por atc","Incidencia ATC"],
  ["readback incorrecto tripulación confirmó altitud equivocada controlador no detectó error","Incidencia ATC"],
  ["callsign confundido atc dio instrucción a otra aeronave creyendo que hablaba con nosotros","Incidencia ATC"],
  ["frecuencia incorrecta dada por atc tripulación perdió contacto con control por minutos","Incidencia ATC"],
  ["clearance incorrecto atc autorizó ruta con conflicto de tráfico TCAS activó resolución","Incidencia ATC"],
  ["pérdida de comunicación con atc por más de diez minutos squawk 7600 activado","Incidencia ATC"],
  ["error de atc resultó en separación inferior al mínimo entre dos aeronaves en ruta","Incidencia ATC"],
  ["controlador asignó nivel de vuelo incorrecto aeronave descendió a nivel con tráfico","Incidencia ATC"],
  ["instrucción de atc de girar a la derecha causó conflicto con tráfico no coordinado","Incidencia ATC"],
  ["atc dio autorización de rodaje por pista activa error de control en tierra incursión","Incidencia ATC"],
  ["confusión de callsigns aerolínea atc autorizó vuelo equivocado a despegar primero","Incidencia ATC"],
  ["perdimos comunicación con torre durante aproximación final imposible restablecer contacto","Incidencia ATC"],
  ["atc no nos dio tiempo para leer back completo y ya nos había cambiado la instrucción","Incidencia ATC"],
  ["ATC gave incorrect descent clearance aircraft descended below assigned altitude conflict","Incidencia ATC"],
  ["controller cleared aircraft to wrong runway runway 18 instead of 01 wrong clearance","Incidencia ATC"],
  ["loss of radio communication squawk 7600 activated followed lost comm procedure","Incidencia ATC"],
  ["ATC callsign confusion cleared wrong aircraft resulted in separation issue traffic","Incidencia ATC"],
  ["readback error not caught by controller aircraft proceeded to wrong waypoint deviation","Incidencia ATC"],
  ["controller gave takeoff clearance with conflicting traffic on runway incursion risk","Incidencia ATC"],
  ["communication failure with approach control during ILS approach no contact established","Incidencia ATC"],
  ["ATC assigned same flight level two aircraft opposite direction head-on conflict TCAS","Incidencia ATC"],
  ["wrong frequency assigned by ATC lost contact for 8 minutes radar contact lost","Incidencia ATC"],
  ["tower cleared us to cross runway 28 runway was active departure was cleared simultaneously","Incidencia ATC"],
  ["instrucción ambigua de atc tripulación interpretó diferente maniobra no esperada por control","Incidencia ATC"],
  ["atc no coordinó transferencia de frecuencia aeronave quedó en frecuencia incorrecta","Incidencia ATC"],
  ["controlador ordenó go around cuando ya teníamos tren abajo y configuración de aterrizaje","Incidencia ATC"],
  ["error en coordinación entre centro y aproximación resultó en dos aeronaves sin separación","Incidencia ATC"],
  // ── INCENDIO (30) ─────────────────────────────────────────────────────────
  ["se declaró incendio en motor número 2 tripulación activó extintor procedimiento completado","Incendio"],
  ["alarma de incendio en motor confirmada llamas visibles desde cabina procedimiento de emergencia","Incendio"],
  ["incendio en tren de aterrizaje detectado en tierra bomberos activados evacuación completa","Incendio"],
  ["fuego en bodega de carga alarma confirmada extintor automático activado aterrizaje de emergencia","Incendio"],
  ["incendio en galley de cabina tripulación sofocó el fuego con extintor de CO2","Incendio"],
  ["wheel fire after landing brakes overheated fire confirmed ground crew extinguished","Incendio"],
  ["engine fire confirmed crew followed QRH fire checklist airfield declared emergency","Incendio"],
  ["cargo hold fire alarm activated automatic halon extinguished diverted nearest airport","Incendio"],
  ["APU fire warning confirmed flames visible APU fire procedure completed successfully","Incendio"],
  ["incendio APU en plataforma antes del vuelo aeronave evacuada extintor activado daños menores","Incendio"],
  ["fuego en motor derecho confirmado por tripulante de cabina visibilidad de llamas pasajeros evacuados","Incendio"],
  ["llamas en ruedas del tren principal tras aterrizaje largo bomberos apagaron incendio pista","Incendio"],
  ["fire in engine number 1 shut down emergency declared extinguisher discharged diverted","Incendio"],
  ["galley oven caught fire flight attendant discharged extinguisher fire contained no injuries","Incendio"],
  ["incendio declarado en cabina eléctrica extintor activado aterrizaje de emergencia exitoso","Incendio"],
  ["fuego en frenos reportado por torre al aterrizar bomberos aeronáuticos intervinieron pista","Incendio"],
  ["engine fire light on confirmed by visual inspection flames from nacelle emergency declared","Incendio"],
  ["cabin fire in rear galley crew extinguished with CO2 extinguisher diversion declared","Incendio"],
  ["incendio confirmado en motor diferente a sospecha de humo fuego real extintor descargado","Incendio"],
  ["aircraft on fire after rejected takeoff brake fire evacuated slides deployed all safe","Incendio"],
  ["se confirmó incendio eléctrico en cabina de equipos extintor activado aterrizaje inmediato","Incendio"],
  ["llamas visibles en nacela motor 1 pasajeros en estado de alerta tripulación siguió QRH","Incendio"],
  ["brake fire confirmed by marshaller after landing taxiway blocked fire trucks responded","Incendio"],
  ["incendio en bodega posterior detectado en vuelo extintor automático activado desviación exitosa","Incendio"],
  ["fire confirmed cargo hold halon system activated diverted emergency declared landing safe","Incendio"],
  ["apu fire on ground crew evacuated aircraft fire brigade extinguished minor damage wing","Incendio"],
  ["fuego eléctrico en panel aviónico extintor descargado en cabina de mando aterrizaje pista","Incendio"],
  ["llamas en motor izquierdo apagado procedimiento completado extintor botella disparada sin daño","Incendio"],
  ["wing fire after heavy landing brake overheated extended into wing fuel tank area evacuated","Incendio"],
  ["incendio real diferenciado de smoke confirmado por tripulación llamas extintor descargado","Incendio"],
  // ── ESTELA TURBULENTA (30) ────────────────────────────────────────────────
  ["aeronave entró en estela turbulenta de heavy anterior fuerte balanceo pasajeros sin cinturón","Estela Turbulenta"],
  ["vórtices de estela causaron actitud inusual roll de 45 grados recuperación inmediata tripulación","Estela Turbulenta"],
  ["wake turbulence encounter on approach severe roll upset recovery required crew reported","Estela Turbulenta"],
  ["wake vortex from preceding heavy aircraft caused rapid roll passengers injured no seatbelt","Estela Turbulenta"],
  ["nos topamos con la estela del heavy que despegó antes separación insuficiente torre ATC","Estela Turbulenta"],
  ["separación de estela insuficiente en aproximación aeronave precedente era categoría heavy","Estela Turbulenta"],
  ["estela turbulenta causó sacudida brusca copas y bandejas cayeron en cabina pasajeros","Estela Turbulenta"],
  ["wake of preceding 747 caused violent roll on short final go around executed immediately","Estela Turbulenta"],
  ["turbulencia por estela de aeronave precedente en ruta ascenso vórtice inesperado","Estela Turbulenta"],
  ["aeronave siguió demasiado cerca al heavy vórtices de estela resultaron en upset momentáneo","Estela Turbulenta"],
  ["wake vortex on departure rolling moment 40 degrees crew recovered manually autopilot off","Estela Turbulenta"],
  ["encontramos estela de otro avión sin advertencia separación mínima no se respetó por atc","Estela Turbulenta"],
  ["vortex encounter from wide-body caused structural stress go around declared wake turbulence","Estela Turbulenta"],
  ["estela del carguero ahead generó balanceo violento durante aproximación final pasajeros heridos","Estela Turbulenta"],
  ["heavy wake turbulence encounter 30 miles behind A380 unexpected vortex upset recovery","Estela Turbulenta"],
  ["vórtice de estela en cruce de ruta aeronave de gran porte rumbo contrario encounter","Estela Turbulenta"],
  ["ATC did not provide sufficient wake turbulence separation aircraft encountered severe wake","Estela Turbulenta"],
  ["balanceo inducido por estela pasajeros heridos en cabina cuatro con lesiones leves","Estela Turbulenta"],
  ["wake vortex encounter on downwind leg unexpected roll crew corrected manually reported atc","Estela Turbulenta"],
  ["estela de avión grande nos hizo rotar involuntariamente en rodaje por vórtice en tierra","Estela Turbulenta"],
  ["wingtip vortex ground effect encountered during takeoff roll preceding aircraft","Estela Turbulenta"],
  ["wake turbulence from departing heavy caused upset to following aircraft in terminal area","Estela Turbulenta"],
  ["passenger injuries due to wake vortex encounter approach phase no seatbelt sign on","Estela Turbulenta"],
  ["aeronave en crucero afectada por vórtices del heavy en paralelo separación lateral insuficiente","Estela Turbulenta"],
  ["wake vortex rolled aircraft 60 degrees before crew recovered severe upset reported asap","Estela Turbulenta"],
  ["estela turbulenta inesperada en ascenso inicial pasajeros sin cinturón en zona de turbulencia","Estela Turbulenta"],
  ["wake of preceding B777 caused momentary loss of control crew declared pan pan immediately","Estela Turbulenta"],
  ["vortex encounter caused overhead bins to open items fell passengers wake turbulence severe","Estela Turbulenta"],
  ["separation from preceding super heavy insufficient wake vortex encountered on approach","Estela Turbulenta"],
  ["estela causó actitud inusual 50 grados de balanceo recuperación manual exitosa reportado","Estela Turbulenta"],
  // ── ILUMINACIÓN LÁSER (30) ────────────────────────────────────────────────
  ["láser verde apuntó directamente al cockpit durante final de aproximación deslumbramiento","Iluminación Láser"],
  ["haz de láser iluminó cabina de mando tripulación reportó deslumbramiento temporal visión","Iluminación Láser"],
  ["laser strike reported on approach green laser from ground blinded copilot momentarily","Iluminación Láser"],
  ["laser attack cockpit final approach green beam pilot vision affected reported authorities","Iluminación Láser"],
  ["piloto reportó deslumbramiento por láser durante despegue visión afectada temporalmente","Iluminación Láser"],
  ["laser illumination reported from port side during climb out green laser ground attack","Iluminación Láser"],
  ["láser rojo apuntó a tripulación durante descenso inicial reportado a torre inmediatamente","Iluminación Láser"],
  ["copiloto cegado momentáneamente por láser verde capitán asumió controles procedimiento","Iluminación Láser"],
  ["green laser strike during approach crew reported temporary vision impairment ATC notified","Iluminación Láser"],
  ["laser dazzle event cockpit both pilots affected landing continued safely laser reported","Iluminación Láser"],
  ["se apuntó con láser al cockpit múltiples veces durante la aproximación denuncia policial","Iluminación Láser"],
  ["laser beam hit windshield on final approach captain temporarily unable to see instruments","Iluminación Láser"],
  ["blue laser struck cockpit during night approach severe flash blindness crew reported","Iluminación Láser"],
  ["ataque con láser reportado en dos vuelos consecutivos mismo punto geográfico tierra","Iluminación Láser"],
  ["laser incident reported at 4000 feet on final approach green laser temporary flash","Iluminación Láser"],
  ["tripulación reportó tres flashes de láser durante la aproximación a la pista 28","Iluminación Láser"],
  ["laser strike first officer affected go around considered continued approach safely","Iluminación Láser"],
  ["láser apuntado desde área residencial próxima al aeropuerto coordenadas reportadas a policía","Iluminación Láser"],
  ["crew reported laser attack on climbout laser strike from ground level metropolitan area","Iluminación Láser"],
  ["deslumbramiento por láser durante vuelo nocturno tripulación completó vuelo reportó incidente","Iluminación Láser"],
  ["laser from vessel at sea illuminated cockpit during approach maritime report filed","Iluminación Láser"],
  ["múltiples incidentes de láser en el mismo corredor de aproximación reporte a autoridad civil","Iluminación Láser"],
  ["both pilots temporarily affected by high-powered green laser during final approach night","Iluminación Láser"],
  ["láser rojo apuntado al cockpit copiloto con irritación ocular después del vuelo reportado","Iluminación Láser"],
  ["laser attack during instrument approach in IMC conditions additional risk crew reported","Iluminación Láser"],
  ["haz láser de alta potencia impactó windshield durante aproximación ILS noche reportado","Iluminación Láser"],
  ["laser incident from area adjacent taxiway aircraft on ground crew reported illumination","Iluminación Láser"],
  ["visión del capitán afectada por láser durante ascenso inicial copiloto asumió controles","Iluminación Láser"],
  ["laser strike en subida inicial desde aeropuerto coordenadas GEO reportadas a policía aeronáutica","Iluminación Láser"],
  ["laser attack second approach crew reported to ATC both pilots describe dazzle effect","Iluminación Láser"],
  // ── FATIGA DE TRIPULACIÓN (30) ────────────────────────────────────────────
  ["tripulación reportó fatiga severa después de múltiples sectores seguidos sin descanso adecuado","Fatiga de Tripulación"],
  ["piloto reportó somnolencia durante crucero tripulante de refuerzo asumió controles fatiga","Fatiga de Tripulación"],
  ["FDP excedió límite reglamentario por demoras operacionales tripulación fatigada no apta","Fatiga de Tripulación"],
  ["copiloto se quedó dormido durante crucero capitán solo en cabina informó fatiga al descender","Fatiga de Tripulación"],
  ["crew reported fatigue after extended duty period FDP exceeded rest requirements violated","Fatiga de Tripulación"],
  ["pilot filed fatigue report after completing duty 14 hours without adequate rest period","Fatiga de Tripulación"],
  ["flight attendant reported inability to concentrate due to insufficient rest fatigue report","Fatiga de Tripulación"],
  ["tripulación forzada a volar sin el descanso mínimo requerido por presión operacional base","Fatiga de Tripulación"],
  ["both crew members fell asleep on autopilot during cruise overflew destination by miles","Fatiga de Tripulación"],
  ["tripulante de cabina no pudo realizar procedimiento de emergencia correctamente por fatiga","Fatiga de Tripulación"],
  ["piloto reportó microsueño durante aproximación inicial despertó al activar alarma GPWS","Fatiga de Tripulación"],
  ["crew fatigue report filed after red-eye overnight flight multiple sectors turnaround","Fatiga de Tripulación"],
  ["fatigue report filed pilot extended duty 16 hours rest period before flight was 6 hours","Fatiga de Tripulación"],
  ["capitán reportó fatiga incapacitante debida a cambio de zona horaria vuelo transoceánico","Fatiga de Tripulación"],
  ["copiloto reportó microsueño durante descenso inicial después de turno largo sin descanso","Fatiga de Tripulación"],
  ["tripulación durmió durante el vuelo sin informar fatiga antes del despegue error grave","Fatiga de Tripulación"],
  ["duty time exceeded maximum allowable FDP crew reported fatigue on arrival FRMS triggered","Fatiga de Tripulación"],
  ["reporte de fatiga piloto durmió menos de cuatro horas en sala de tripulación voló igual","Fatiga de Tripulación"],
  ["pilot reported severe fatigue after three consecutive night duties cumulative sleep debt","Fatiga de Tripulación"],
  ["crew fatigue identified during ASAP debrief crew fell asleep on final approach recovered","Fatiga de Tripulación"],
  ["ambos pilotos reportaron sentirse extremadamente cansados antes del vuelo pero operaron igual","Fatiga de Tripulación"],
  ["reporte de fatiga FRMS tripulación no fit for duty por descanso insuficiente vuelo cancelado","Fatiga de Tripulación"],
  ["fatigue incident copilot fell asleep during climb phase captain noticed crew rested briefly","Fatiga de Tripulación"],
  ["tripulación en tercer sector del día reportó fatiga extrema errores en checklist detectados","Fatiga de Tripulación"],
  ["pilot fatigue report rest hotel had loud party sleep disrupted next flight performance affected","Fatiga de Tripulación"],
  ["extended operational delay resulted in FDP exceedance crew fatigued filed safety report","Fatiga de Tripulación"],
  ["cabin crew reported inability to complete safety procedures due to fatigue multiple sectors","Fatiga de Tripulación"],
  ["tripulación no fit no informó al despacho sobre fatiga voló mismo y ocurrió error grave","Fatiga de Tripulación"],
  ["fatigue risk management system trigger crew had cumulative fatigue three days duty period","Fatiga de Tripulación"],
  ["rest requirement violated captain pressured to fly despite insufficient rest period safety","Fatiga de Tripulación"],
  // ── ERROR DE NAVEGACIÓN (30) ──────────────────────────────────────────────
  ["tripulación ingresó waypoint incorrecto en FMS aeronave desvió 50 millas de la ruta","Error de Navegación"],
  ["aeronave siguió ruta incorrecta por error en programación del FMS waypoint equivocado","Error de Navegación"],
  ["wrong runway approach begun crew followed ILS for runway 10 instead of runway 28","Error de Navegación"],
  ["navigation error aircraft off course by 40 miles crew noticed deviation from expected track","Error de Navegación"],
  ["RNAV approach used incorrect procedure plate waypoints wrong approach chart confusion","Error de Navegación"],
  ["GPS jamming detected in airspace navigation reverted to conventional ILS position uncertain","Error de Navegación"],
  ["GPS spoofing event aircraft received false position information FMS showed incorrect position","Error de Navegación"],
  ["piloto ingresó QNH incorrecto altímetro mostraba 300 pies más alto que real riesgo terrain","Error de Navegación"],
  ["wrong QNH set altimeter error terrain proximity warning GPWS activated due nav error","Error de Navegación"],
  ["ILS falso detectado aeronave comenzó aproximación a localizer falso go around ejecutado","Error de Navegación"],
  ["false ILS signal captured aircraft deviated below glidepath crew noticed go around safe","Error de Navegación"],
  ["RNAV waypoint database cycle expired nav database outdated wrong procedure executed","Error de Navegación"],
  ["base de datos de navegación vencida aeronave siguió procedimiento desactualizado peligroso","Error de Navegación"],
  ["piloto confundió procedimiento SID seleccionó ruta incorrecta en FMS desvío inicial","Error de Navegación"],
  ["wrong SID programmed in FMC aircraft turned wrong direction after takeoff ATC caught","Error de Navegación"],
  ["error de altímetro tripulación estableció nivel de vuelo incorrecto conflicto tráfico TCAS","Error de Navegación"],
  ["aircraft navigated to wrong destination crew misidentified waypoints incorrect flight plan","Error de Navegación"],
  ["tripulación siguió a waypoint incorrecto que no estaba en plan de vuelo desviación rutera","Error de Navegación"],
  ["FMS programming error resulted in wrong course flown ATC identified deviation immediately","Error de Navegación"],
  ["GPS position error during oceanic crossing aircraft off track by 2 degrees hours undetected","Error de Navegación"],
  ["aeronave inició aproximación a aeropuerto equivocado confusión de similitud de nombre","Error de Navegación"],
  ["pilot selected incorrect approach procedure for active runway wrong runway ILS frequency","Error de Navegación"],
  ["navigation database expired waypoints missing FMS showed invalid route flown incorrectly","Error de Navegación"],
  ["GNSS signal lost during precision approach crew reverted to raw data ILS navigation","Error de Navegación"],
  ["pérdida de señal GNSS en zona montañosa RAIM insuficiente desvío de ruta reportado","Error de Navegación"],
  ["wrong STAR programmed crew flew to unexpected waypoint ATC intervened corrected route","Error de Navegación"],
  ["ILS frequency incorrectly set approach captured wrong ILS crew noticed late go around","Error de Navegación"],
  ["error de navegación ruta aeronave cruzó espacio aéreo restringido sin autorización NOTAM","Error de Navegación"],
  ["crew entered wrong coordinates in FMC aircraft heading to waypoint 200 miles off plan","Error de Navegación"],
  ["navigation error oceanic track wrong crew filed incorrect track message ATC corrected","Error de Navegación"],

];

// ── Naive Bayes: entrenamiento ────────────────────────────────────────────

module.exports = { NB_CORPUS };
